name: Build then test

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "ci" ]

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
      sudo apt-get install -y gcc g++ clang libpng-dev libjpeg-dev libmagick++-dev libimath-dev
      sudo apt-get install -y libgraphicsmagick++-dev libfftw3-dev zlib1g-dev libheif-dev
    - name: build
      run:  |
      pushd examples
      make clean
      make mlinux
      popd

 build-on-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: brew install libheif libpng libfftw3 libjpeg gcc g++ clang zlib libmagick++ libgraphicsmagick++ openexr
    - name: Install make
      run: brew install automake
    - name: build
      run: |
      pushd examples
      make clean
      make mmacos
      popd
